### Первая часть

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

#### Решение

а) $AB$ и $BA$ матрицы не определены

б) $AB$ - матрица $2 \times 3$, $BA$ матрица не определена 

в) $AB$ - матрица $8 \times 8$, $BA$ - матрица $3 \times 3$

с) $AB$ и $BA$ - квадратные матрицы $4 \times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

#### Решение

$A + B =\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$ <br>
$AB=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
A + B

array([[ 5, -3],
       [ 3,  5]])

In [3]:
A.dot(B)

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

#### Решение

$3A - 2B + 4C =\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [4]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

#### Решение

$A^{T}=\begin{pmatrix}
4 & 5 & 2 \\
1 & -2 & 3
\end{pmatrix}$

$AA^{T}=\begin{pmatrix}
16 + 1 & 20 - 2 & 8 + 3 \\
20 - 2 & 25 + 4 & 10 - 6 \\
8 + 3 & 10 - 6 & 4 + 9
\end{pmatrix}$ =
$\begin{pmatrix}
17 & 18 & 11 \\
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}$

$A^{T}A = \begin{pmatrix}
16 + 25 + 4 & 4 - 10 + 6 \\
4 - 10 + 6 & 1 + 4 + 9
\end {pmatrix}$ = 
$\begin{pmatrix}
45 & 0 \\
0 & 14
\end {pmatrix}$

In [5]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A.dot(A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [6]:
(A.T).dot(A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

#### Решение

In [7]:
def matrix_multiply(A,B):
    n = A.shape[0]
    m = A.shape[1]
    k = B.shape[0]
    s = B.shape[1]
    if m != k:
        print(f'Матрицы невозможно перемножить, так как количество строк 2-ой матрицы = {k} /nи' 
              'оно не совпадает с количеством столбцов 1-ой матрицы = {m}')
    else:
        Matrix = [[0 for x in range(s)] for y in range(n)] 
        for i in range(n):
            for j in range(s):
                w = 0
                while w < m:
                    Matrix[i][j] += A[i][w]*B[w][j]
                    w += 1
    return Matrix

In [8]:
B = A.T

In [9]:
for row in matrix_multiply(A,B):
    print(row)

[17, 18, 11]
[18, 29, 4]
[11, 4, 13]


### Вторая часть
Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

#### Решение

   a)

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}$ =
$sin^{2}x -(-cos^{2}x)$ = 1

   б)
    
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}$ =
$4 \times 5 \times 9$ = 180 
    
   в) отнимем из 3-ей строки (1 строку х 3), из 2-ой строки (1 строку х 2), получившиеся 2 и 3 строки явно Л.З.

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}$ = 
$\begin{vmatrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
4 & 2 & 0
\end{vmatrix}$ = 0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

#### Решение

  а) $det(A^{2})$ = $det(A) \times det(A)$ = 16
    
   б) $det(A^{T})$ = $det(A)$ = 4
    
   в) $det(2A)$ = $2^{rank(A)} \times det(A)$ =  $2^{rank(A)} \times 4$ = $2^{rank(A) + 2}$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

#### Решение

Умножим 1-ую строку на 2 и сложим со 2-ой:<br>
$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$ =
$\begin{pmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{pmatrix}$ <br>
Т.к. в строке все члены = 0, то определитель = 0 => матрица вырожденная.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

#### Решение

   а) Отнимем из 1-ой строки 2-ю, из 3-ей отнимем 2-ую $\times 2$: <br> 
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$ =
$\begin{pmatrix}
0 & 1 & 2\\ 
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix}$ <br>
Т.к. 2 строки из 3-х являются Л.З. => ранг = 2

In [10]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(A)

2

   б) Из 2-ой строки отнимем 1-ую, из 3-ей строки отнимем 1-ую $\times 2$= <br> 
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$ =
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 1\\ 
2 & 3 & 5 & 6
\end{pmatrix}$ <br>
Т.к. из 4 строк 2 строки Л.З. => rank = 3

In [11]:
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(B)

3